version: "3"

services:
  taco_meteor:
    build: ./application
    container_name: taco_meteor
    ports:
      - "8000:3000"
    volumes:
      - ./data/application:/usr/taco/application
    networks: 
      - taco_network
  
  taco_mongo:
    image: mongo:3.2
    container_name: taco_mongo
    volumes:
      - taco-mongo:/data/db
    ports:
      - "27017:27017"
    networks: 
      - taco_network

  taco_db_interface:
    image: mongo-express
    container_name: taco_db_interface
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: taco
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: taco_mongo
    networks: 
      - taco_network

networks:
  taco_network:
volumes:
  taco-mongo: