version: "3"

services:
  taco_api:
    image: node:alpine
    container_name: taco_api
    expose:
      - "80"
    ports:
      - "8000:8000"
    volumes:
      - ./data/api:/usr/taco/api
    working_dir: /usr/taco/api
    command: npm run start
    networks:
      - taco_network

  taco_application:
    image: node:alpine
    container_name: taco_application
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./data/application:/usr/taco/application
    working_dir: /usr/taco/application
    command: npm run start
    networks:
      - taco_network
  
  taco_mongo:
    image: mongo:3.2
    container_name: taco_mongo
    volumes:
      - taco-mongo:/data/db
    ports:
      - "27017:27017"
    networks: 
      - taco_network

  taco_db_interface:
    image: mongo-express
    container_name: taco_db_interface
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: taco
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: taco_mongo
    networks: 
      - taco_network

networks:
  taco_network:
volumes:
  taco-data:
  taco-mongo: